# Generated by Django 4.2.5 on 2023-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='characterpair',
            field=models.CharField(default='', max_length=50),
        ),
    ]
