# Generated by Django 4.2.5 on 2023-09-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_characterpair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='character',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='characterpair',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessage',
            unique_together={('game_code', 'characterpair')},
        ),
    ]
