# Generated by Django 4.2.5 on 2023-09-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('characterpair', models.CharField(default='', max_length=50)),
            ],
            options={
                'unique_together': {('game_code', 'characterpair')},
            },
        ),
    ]
